"""
Phase 2 weekly routine: compare live paper-trading metrics vs backtest baseline.

Flags any metric that is > 2 standard deviations from its backtest mean.
Two consecutive weeks of drift on the same metric = STOP signal.

Usage:
  python scripts/drift_check.py [--paper] [--days 30]

Reads:
  - data/trades.db       (live paper trades)
  - data/backtest_baseline.json  (generated by backtester; created if absent)

Outputs:
  - drift report to stdout
  - exit code 0 = all clear, 1 = drift detected
"""

import argparse
import json
import math
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv()

BASELINE_PATH = Path("data/backtest_baseline.json")

# ── Default backtest baseline (fallback if no backtest has been run) ──────────

DEFAULT_BASELINE = {
    "sharpe_ratio":   {"mean": 1.5,  "std": 0.5},
    "win_rate":       {"mean": 0.55, "std": 0.08},
    "avg_ev":         {"mean": 0.07, "std": 0.03},
    "trades_per_day": {"mean": 5.0,  "std": 3.0},
    "brier_score":    {"mean": 0.20, "std": 0.04},
    "veto_rate":      {"mean": 0.35, "std": 0.15},
}

SIGMA_THRESHOLD = 2.0   # flag if metric deviates by more than 2 std


def load_baseline() -> dict:
    if BASELINE_PATH.exists():
        with open(BASELINE_PATH) as f:
            return json.load(f)
    print(f"[INFO] No baseline at {BASELINE_PATH} — using hardcoded defaults.")
    print("[INFO] Run a full backtest and save results to generate a real baseline.")
    return DEFAULT_BASELINE


def compute_live_metrics(days: int, paper: bool) -> dict:
    """Query the DB for metrics over the last `days` calendar days."""
    import sqlite3

    db = Path("data/trades.db")
    if not db.exists():
        return {}

    since = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()[:19]
    conn = sqlite3.connect(str(db))
    conn.row_factory = sqlite3.Row

    paper_flag = 1 if paper else 0

    rows = conn.execute(
        "SELECT outcome, pnl_usdc, ev, our_prob, confidence, timestamp "
        "FROM trades WHERE paper=? AND timestamp >= ?",
        (paper_flag, since),
    ).fetchall()
    conn.close()

    if not rows:
        return {}

    total = len(rows)
    resolved = [r for r in rows if r["outcome"] in ("WIN", "LOSS", "VOID")]
    wins  = sum(1 for r in resolved if r["outcome"] == "WIN")
    losses = sum(1 for r in resolved if r["outcome"] == "LOSS")
    open_  = [r for r in rows if r["outcome"] is None or r["outcome"] == "OPEN"]

    win_rate = wins / len(resolved) if resolved else 0.0
    avg_ev   = sum(r["ev"] or 0 for r in rows) / total if total else 0.0

    pnls = [r["pnl_usdc"] or 0 for r in resolved]
    if len(pnls) > 1:
        mean_pnl = sum(pnls) / len(pnls)
        std_pnl  = math.sqrt(sum((p - mean_pnl) ** 2 for p in pnls) / len(pnls))
        sharpe   = (mean_pnl / std_pnl) * math.sqrt(252) if std_pnl > 0 else 0.0
    else:
        sharpe = 0.0

    # Brier score on resolved trades where we have our_prob
    brier_rows = [r for r in resolved if r["our_prob"] is not None]
    if brier_rows:
        brier = sum(
            (r["our_prob"] - (1.0 if r["outcome"] == "WIN" else 0.0)) ** 2
            for r in brier_rows
        ) / len(brier_rows)
    else:
        brier = 0.0

    trades_per_day = total / days if days > 0 else 0.0
    veto_rate = 0.0  # Can't compute without veto log; report as 0

    return {
        "sharpe_ratio":   sharpe,
        "win_rate":       win_rate,
        "avg_ev":         avg_ev,
        "trades_per_day": trades_per_day,
        "brier_score":    brier,
        "veto_rate":      veto_rate,
        "total_trades":   total,
        "resolved":       len(resolved),
        "wins":           wins,
        "losses":         losses,
    }


def run_drift_check(days: int = 30, paper: bool = True) -> int:
    baseline = load_baseline()
    live     = compute_live_metrics(days, paper)

    if not live:
        print("[WARN] No live trades found in the last %d days. Nothing to compare." % days)
        return 0

    print(f"\n{'='*65}")
    print(f"Drift Check  |  last {days} days  |  {'paper' if paper else 'live'}")
    print(f"{'='*65}")
    print(f"{'Metric':<22} {'Live':>10} {'Baseline':>12} {'Sigma':>8}  Status")
    print(f"{'-'*65}")

    drifted = []
    for metric, base in baseline.items():
        live_val = live.get(metric)
        if live_val is None:
            continue
        mean = base["mean"]
        std  = base["std"]
        sigma = (live_val - mean) / std if std > 0 else 0.0
        abs_sigma = abs(sigma)
        status = "OK"
        if abs_sigma > SIGMA_THRESHOLD:
            status = "DRIFT"
            drifted.append((metric, sigma))
        flag = " <-- DRIFT" if status == "DRIFT" else ""
        print(f"  {metric:<20} {live_val:>10.4f} {mean:>12.4f} {sigma:>+8.2f}s  {status}{flag}")

    print(f"\n  Total trades last {days}d: {live['total_trades']}  "
          f"(resolved: {live['resolved']}, wins: {live['wins']}, losses: {live['losses']})")

    if drifted:
        print(f"\n[DRIFT DETECTED] {len(drifted)} metric(s) exceed {SIGMA_THRESHOLD}s:")
        for m, s in drifted:
            direction = "HIGH" if s > 0 else "LOW"
            print(f"  - {m}: {abs(s):.1f}s {direction}")
        print("\nAction: investigate root cause before next scale-up.")
        return 1

    print("\n[CLEAR] All metrics within normal range.")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Weekly drift check")
    parser.add_argument("--days",  type=int, default=30, help="Lookback window in days")
    parser.add_argument("--live",  action="store_true",  help="Check live trades (default: paper)")
    args = parser.parse_args()
    sys.exit(run_drift_check(days=args.days, paper=not args.live))
